apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: {{ .Values.service.type }}
